[project]
name = "uv-macrosproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "afcta", email = "andreasjensvoll@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "kivy>=2.3.1",
    "rapidfuzz>=3.14.6",
]

[project.scripts]
uv-macrosproject = "uv_macrosproject:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
